### ISSUE TITLE
Cannot read property 'sirv' of undefined (frontend JS error)

### ISSUE THREAD

**Issue by florisschreuder** [sirv/magento2#1]
Hi,

On a new shop where Sirv has not been configured yet, but the module is installed, we're getting this error:

`Uncaught TypeError: Cannot read property 'sirv' of undefined
    at Object.<anonymous> (text.min.js:1)
    at Object.execCb (ee2cc9b32167b0c055258f510b51a582.min.js:112)
    at Module.check (ee2cc9b32167b0c055258f510b51a582.min.js:56)
    at Module.<anonymous> (ee2cc9b32167b0c055258f510b51a582.min.js:72)
    at ee2cc9b32167b0c055258f510b51a582.min.js:11
    at ee2cc9b32167b0c055258f510b51a582.min.js:74
    at each (ee2cc9b32167b0c055258f510b51a582.min.js:3)
    at Module.emit (ee2cc9b32167b0c055258f510b51a582.min.js:74)
    at Module.check (ee2cc9b32167b0c055258f510b51a582.min.js:61)
    at Module.enable (ee2cc9b32167b0c055258f510b51a582.min.js:73)`

This error is apparently dependent upon the module being both configured AND _on_.

We also can't easily remove the text.js file from loading, because it looks to be initialized via an override in de requirejs-config.js.

**Comment by florisschreuder** [comment]
Hi @ishugurov 

The problem is in this file:
https://github.com/sirv/sirvmagento2/blob/master/view/frontend/web/js/text.js (it's minified in my customer's shop because they use the Magento feature of JS minification)

If I understand what's happening:
In this file (https://github.com/sirv/sirvmagento2/blob/master/view/frontend/templates/html/head.phtml#L34-L46) you set configuration in JS for the text.js file.
However, on this line (https://github.com/sirv/sirvmagento2/blob/master/view/frontend/templates/html/head.phtml#L17-L19) you check if the module is **enabled** or not. If not, you return an empty PHTML file.

However, on these lines (https://github.com/sirv/sirvmagento2/blob/master/view/frontend/web/js/text.js#L15-L19) you have no exception handling in case the config was never set. So you get a JS error on the frontend if the module is disabled which breaks the entire RequireJS chain (breaking _all_ of the javascript on the page).

**Comment by ishugurov** [comment]
Thank you for clarification, will be fixed soon.

**Comment by ishugurov** [comment]
Issue has been resolved in the 3.2.4 [https://github.com/sirv/sirvmagento2/tree/3.2.4](url)
